version: 2.1

references:
    set_npm_token: &set_npm_token
        run:
            name: Add NPM auth token file
            command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-1-{{ checksum "yarn.lock" }}

            - run: yarn

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-1-{{ checksum "yarn.lock" }}

            - persist_to_workspace:
                  root: "."
                  paths:
                      - ./*
                      - node_modules
                      - yarn.lock
                      - src

    format:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn format

    lint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn lint

    publish:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - *set_npm_token

            - attach_workspace:
                  at: "."

            - run: npm publish || exit 0

    lint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn test

workflows:
    version: 2
    build_and_verify:
        jobs:
            - build
                      - test
            - format:
                  requires:
                      - build
            - lint:
                  requires:
                      - build
            - publish:
                  filters:
                      branches:
                          only: master
                  requires:
                      - build
                      - format
                      - lint
            - test:
                  requires:
                      - build
